### ISSUE TITLE
Heroku and Direct Link

### ISSUE THREAD

**Issue by anonymous060104** [FayasNoushad/Pixeldrain-Bot#11]
how to deploy bot to heroku and can it upload direct link like gd index to pixeldrain?

**Comment by FayasNoushad** [comment]
Fork this repository, create a project on heroku, connect your forked repository, add variables, deploy branch.

**Comment by FayasNoushad** [comment]
Download page example:- https://pixeldrain.com/u/FNss9Bhs
Direct example:- https://pixeldrain.com/api/file/FNss9Bhs

**Comment by anonymous060104** [comment]
it give me error, where to add variables?
2024-03-25T19:43:16.247133+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=pixeldrain060104-a7f6a91708be.herokuapp.com request_id=8bb6bf35-d349-4d13-a8e8-012c9348725a fwd="114.124.236.146" dyno= connect= service= status=503 bytes= protocol=https

**Comment by FayasNoushad** [comment]
> it give me error, where to add variables? 2024-03-25T19:43:16.247133+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=pixeldrain060104-a7f6a91708be.herokuapp.com request_id=8bb6bf35-d349-4d13-a8e8-012c9348725a fwd="114.124.236.146" dyno= connect= service= status=503 bytes= protocol=https

https://devcenter.heroku.com/articles/config-vars#using-the-heroku-dashboard
