### ISSUE TITLE
Error after finish uploading message

### ISSUE THREAD

**Issue by hatoyski** [FayasNoushad/Pixeldrain-Bot#3]
This message appear on bot after uploading message Error :- 'Response' object is not subscriptable

No log on heruko though.

**Comment by FayasNoushad** [comment]
Then how you saying that error after uploading

**Comment by hatoyski** [comment]
that error message dispalying on bot after saying its uploaded not from heroku because no log from it
![1](https://user-images.githubusercontent.com/90185845/144732307-efa43bf4-75ce-4a6d-8d7f-8171a13285a3.PNG)
.

**Comment by FayasNoushad** [comment]
I think you uploaded audio/music

**Comment by hatoyski** [comment]
I think all files

![3](https://user-images.githubusercontent.com/90185845/144734001-71a3d94e-00a0-44f7-b54c-e7c5b5ba9640.PNG)
![4](https://user-images.githubusercontent.com/90185845/144734006-2f4bb134-69d9-4b65-9fcf-af84241466c0.PNG)

**Comment by FayasNoushad** [comment]
Fetch merge and deploy branch
