### ISSUE TITLE
Response object is not subscriptable error again

### ISSUE THREAD

**Issue by rsoorajs** [FayasNoushad/Pixeldrain-Bot#8]
Telegram error,no error logs in heroku

```
Error :- `'Response' object is not subscriptable`

Download Successfully
Upload Successfully
```

**Comment by rsoorajs** [comment]
Duplicate error

https://github.com/FayasNoushad/Pixeldrain-Bot/issues/5

**Comment by rsoorajs** [comment]
Getting this error after showing "Uploaded successfully " message

**Comment by rsoorajs** [comment]
> Try now

worked finally.Thank you for fixing

**Comment by FayasNoushad** [comment]
> > Try now
> 
> worked finally.Thank you for fixing

Thanks for reporting that
